#!/usr/bin/env tsx
/**
 * Build `web/src/lib/figures/dessinScientifiqueIr.ts` from the hand-authored épure IRs.
 *
 * Input:  figures/dessin-scientifique/ir/*.json — one EpureIR per sub-figure, written by a human
 *         from the authored SVG (scripts/digest-epure-svg.mjs assists; it never decides).
 * Output: one generated TS module keyed `page:blockId`, arrays because one sheet can hold
 *         several sub-figures (fig02 = E61 b + c).
 *
 *   npm run build:epure-ir
 *
 * Every IR is run through the SAME validator the app uses (imported from the TS source — one
 * source of truth), and its page/blockId is cross-checked against manifest.json. A mismatch is
 * refused, never guessed into place: a reconstruction bound to the wrong block would render
 * confident 3D under somebody else's figure.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { validateEpureIr, type EpureIR } from '../web/src/lib/epureIr';
import { reconstruct } from '../web/src/lib/epureReconstruct';

const DIR = path.resolve('figures/dessin-scientifique');
const IR_DIR = path.join(DIR, 'ir');

const manifest: { n: number; page: number; blockId: string }[] = JSON.parse(
  readFileSync(path.join(DIR, 'manifest.json'), 'utf8'),
);
const byN = new Map(manifest.map((m) => [m.n, m]));

const files = readdirSync(IR_DIR).filter((f) => /^fig\d+[a-z]?\.json$/.test(f)).sort();
const entries: { key: string; ir: EpureIR; file: string }[] = [];
const problems: string[] = [];

for (const file of files) {
  const raw = JSON.parse(readFileSync(path.join(IR_DIR, file), 'utf8'));
  const val = validateEpureIr(raw);
  if (!val.ok) {
    problems.push(`${file}: invalid IR:\n${val.errors.map((e) => `    ${e.path}: ${e.message}`).join('\n')}`);
    continue;
  }
  const ir = val.ir;
  const m = byN.get(ir.source.n);
  if (!m) {
    problems.push(`${file}: source.n=${ir.source.n} is not in manifest.json`);
    continue;
  }
  if (m.page !== ir.source.page || m.blockId !== ir.source.blockId) {
    problems.push(
      `${file}: source says page ${ir.source.page} block ${ir.source.blockId}, ` +
        `but manifest binds fig ${ir.source.n} to page ${m.page} block ${m.blockId}`,
    );
    continue;
  }
  // An IR that cannot be reconstructed is a wrong reading — refuse it at build time, where the
  // author is looking, instead of shipping a dead button.
  const recon = reconstruct(ir);
  if (recon.fatal) {
    problems.push(`${file}: reconstruction is fatal: ${recon.warnings.map((w) => w.message).join('; ')}`);
    continue;
  }
  for (const w of recon.warnings) {
    console.warn(`note ${file}: ${w.code} — ${w.message}`);
  }
  entries.push({ key: `${ir.source.page}:${ir.source.blockId}`, ir, file });
}

if (problems.length) {
  console.error(`REFUSED (${problems.length}):\n${problems.map((p) => `  ${p}`).join('\n')}`);
  process.exit(1);
}

const byKey = new Map<string, EpureIR[]>();
for (const e of entries) {
  const list = byKey.get(e.key) ?? [];
  list.push(e.ir);
  byKey.set(e.key, list);
}

const body = [...byKey.entries()]
  .map(([key, irs]) => {
    const label = irs.map((ir) => `fig ${ir.source.n}${ir.source.sub ?? ''}`).join(', ');
    return `  // ${label}\n  ${JSON.stringify(key)}: ${JSON.stringify(irs)},`;
  })
  .join('\n');

const out = `import type { EpureIR } from '../epureIr';

/**
 * GENERATED by scripts/build-epure-ir.mts — do not edit by hand; edit
 * figures/dessin-scientifique/ir/*.json and re-run \`npm run build:epure-ir\`.
 *
 * Hand-authored Intermediate Representations of the épures: WHAT each figure contains, in pixel
 * space, no 3D anywhere. The 3D shown in the app is computed from these by epureReconstruct.ts —
 * closed-form geometry, so it is exactly as right as the reading recorded here, no more.
 *
 * Keyed \`page:blockId\` like the authored SVGs; arrays because one sheet holds several épures.
 */
export const DESSIN_SCIENTIFIQUE_IR: Record<string, EpureIR[]> = {
${body}
};
`;

const dest = path.resolve('web/src/lib/figures/dessinScientifiqueIr.ts');
writeFileSync(dest, out);
console.log(`wrote ${entries.length} IRs (${byKey.size} blocks) -> ${dest}`);
